### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by zoomd3v** [yanncam/multiduplicut#3]
Hello

Is there any Possibility to have windows version ?

**Comment by yanncam** [comment]
Hello @zoomd3v,

I have no plans to convert this tool for Windows environments (in Powershell or otherwise). But it can easily be adapted in a cross-platform language (Python for example).

However, you can certainly use it under Windows via WSL (Windows Subsystem for Linux), or via a simple virtual machine.

Happy New Year to you,
